#!/bin/bash

# Check number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
	echo "Usage: cairo-new [--starknet|--polygon] <project-name>"
	exit 1
fi

# Check first argument to decide the action
case "$1" in
	--starknet)
		if [ "$#" -ne 2 ]; then
			echo "Usage: cairo-new --starknet <project-name>"
			exit 1
		fi
		if [ "$2" == "test" ]; then
			echo "Error: Do not name the project as 'test'."
			exit 1
		fi
		echo "Executing for Starknet Project..."
		# Use the command with --starknet here, "$2" will be the <project-name>
		starknet-new $2
		cairo-gitsubmodules $2
		cairo-common $2 STARKNET
		;;
	*)
		if [ "$#" -ne 1 ]; then
			echo "Usage: cairo-new <project-name>"
			exit 1
		fi
		if [ "$1" == "test" ]; then
			echo "Error: Do not name the project as 'test'."
			exit 1
		fi
		echo "Executing for Cairo Project..."
		# Use the normal command here, "$1" will be the <project-name>
		cairo-base $1
		cairo-gitsubmodules $1
		cairo-common $1 CAIRO
		;;
esac

