#!/bin/bash
if [ "$#" -ne 1 ]; then
  echo "Usage: Starknet-new <project-name>"
  exit 1
fi

PROJECT_NAME=$1
mkdir $PROJECT_NAME

# Create Makefile
cat > "${PROJECT_NAME}/Makefile" << 'EOL'
.PHONY: default

# Default target
default: test format

# Test the project
test:
	@cairo-test --starknet .

test_with_args:
	@cairo-test --starknet  . $(ARGS)

format:
	@cairo-format --recursive src/*

compile:
	@mkdir -p artifacts
EOL
echo "	@starknet-compile --allowed-libfuncs-list-name all src/$PROJECT_NAME.cairo artifacts/$PROJECT_NAME.json" >> ${PROJECT_NAME}/Makefile
	
